name: flutter_study_app
description: A Flutter study application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ios风格的图标
  cupertino_icons: any
  # 视频播放器
  video_player: any
  # 设备信息
  device_info: any
  # 轻量数据库
  sqflite: any
  # 网络图片缓存
  cached_network_image: any
  # http请求库,代替http
  dio: any
  # json注解库
  json_annotation: any
  # 缓存
  shared_preferences: any
  # 二维码扫描
  qr_flutter: any
  # 大量的icon图标
  font_awesome_flutter: any
  # state管理工具
  provider: ^4.0.5+1
  # 时间格式化
  intl: any
  # 生成唯一不重复id
  uuid: any
  # 异步处理
  rxdart: any
  # 手机网络状态监控 是wifi还是流量 wifi,mobile
  connectivity: any
  #加密库
  encrypt: any
  # 相机和相册
  image_picker: any
  # 查找文件的位置
  path_provider: any
  # google地图
  google_maps_flutter: any
  # app之间跳转
  url_launcher: any
  # 内置web view
  webview_flutter: any
  # markdown支持
  flutter_markdown: any
  # github库
  flutter_github_api: any
  # markdown editor
  zefyr:

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  build_runner:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/avatar.png
    - assets/images/splash.png
    - assets/images/default_avatar.png
    - assets/images/accountBg.jpg
    - assets/images/login_bg.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
